### ISSUE TITLE
not compatible with pixi.js-legacy

### ISSUE THREAD

**Issue by apptaro** [pixijs/pixi-filters#242]
Filters are not compatible with pixi.js-legacy when using in TypeScript.

**Steps to Reproduce**

install modules:
```
npm install typescript
npm install pixi.js-legacy
npm install @pixi/filter-glow
```
create Test.ts:
```
import * as PIXI from 'pixi.js-legacy';
import { GlowFilter } from '@pixi/filter-glow';

export class Test {
    constructor() {
        const app = new PIXI.Application();
        const glowFilter = new GlowFilter();
    }
}
```
Compile:
```
node_modules\.bin\tsc Test.ts
...
Found 41 errors.
```

The issue is caused by the GlowFilter referencing pixi.js typings here:
https://github.com/pixijs/pixi-filters/blob/master/filters/glow/types.d.ts#L1

Both pixi.js-legacy.d.ts and pixi.js.d.ts are loaded, resulting in duplicate identifier errors.

**Comment by apptaro** [comment]
Workaround is to edit node_modules/@pixi/filter-glow/types.d.ts, and change `"pixi.js"` to `"pixi.js-legacy"` but it will be undo-ed when updating the library.

**Comment by bigtimebuddy** [comment]
You’re right! Good one.

There’s good news and bad news. Good news is that pixi is moving to typescript which will eliminate this issue by having low level imports of package types (eg, `import {Filter} from ‘@pixi/core’`) eliminating the type confusion/duplication. This will be ready in the next release.

The bad news is that, I’m not sure when that’ll be ready and we can fix this issue. Also, I don’t know if there’s a decent workaround that I can implement now. One idea is: Instead of using pixi.js-legacy, you could use http://pixijs.io/customize to create your own bundle plus add pixi.js. That should not create the type confusion. I’ll see if I can put an example together. Open to suggestions?

**Comment by apptaro** [comment]
there are other issues with pixi.js + typescript such as:
- pixi customize has issues with typescript: https://github.com/pixijs/customize/issues/8
- @pixi packages don't have typings: https://github.com/pixijs/pixi.js/issues/6016
Maybe it is just better to wait the next release...

**Comment by bigtimebuddy** [comment]
Agreed, thanks for reporting the issue. This hopefully should get squared soon

**Comment by qk0106** [comment]
Any update to this one?

**Comment by bigtimebuddy** [comment]
5.4.0 release of pixi will have package typings. We are just working out those bits now. Close!

**Comment by bigtimebuddy** [comment]
Still an issue, will get resolved soon with next PixiJS release.

**Comment by bigtimebuddy** [comment]
This should be fixed now with PixiJS v6 and Filters v4. We introduced package typings which means that we no longer reference types in `pixi.js` so this should be compatible with legacy.
