### ISSUE TITLE
[SUGGEST]Manage shader's source with  ES6 standard method.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-filters#50]
@bigtimebuddy I refactor my custom Filter and use common `export string` & `import string` &  `template string`  like this :

```js
import commonHead from '../_shared/common-head.frag.js';
import loadDiffuse from '../_shared/load-diffuse.frag.js';
import loadNormal from '../_shared/load-normal.frag.js';
import computeNormal from '../_shared/compute-normal.frag.js';

export default `

${commonHead}

void main(void)
{

${loadDiffuse}
${loadNormal}

    uViewSize;

    // simplified lambert shading that makes assumptions for ambient color

    // compute Distance
    float D = 1.0;

${computeNormal}

    vec3 L = vec3(1.0, 1.0, 1.0);

    // pre-multiply light color with intensity
    // then perform "N dot L" to determine our diffuse
    vec3 diffuse = uLightColor * max(dot(N, L), 0.0);

    vec3 finalColor = diffuseColor.rgb * diffuse;

    gl_FragColor = vec4(finalColor, diffuseColor.a);
}

`;

```

then use 

```
import vertex from './ambient.vert.js';
import fragment from './ambient.frag.js';

```  
in Filter js file.

I think this way is standard and more common . It's better than using `glslify`(pixi 4.0) or `readFileSync`(pixi 4.5)  or rollup's rule(pixi-filters).

**Comment by englercj** [comment]
The unfortunate part about this is that all other tooling related to writing these shaders breaks (syntax highlighting, compilation checking, etc).

**Comment by bigtimebuddy** [comment]
@finscn's approach is useful if you need to compose multiple fragments. It can help reduce common code and to create better maintainability and encapsulation of functionality. The tradeoff, like @englercj is that it makes the shaders less friendly with outside tools. 

Since we don't have a big need to compose multiple fragments (other than maybe Godray #40), there isn't really a big need to convert **.frag** files to JS modules for the purpose of templating. And the common code eliminated is so small, the tradeoff doesn't seem worth it.

Interesting approach, but not the right choice for **pixi-filters**.

**Comment by bigtimebuddy** [comment]
@finscn, you are proposing more complexity for little reward. Introducing a lot of hidden magic into the build process is not a big win.

What problem are you trying to solve? If you want to chop a bunch of small files into even smaller files so that you can reuse single lines (e.g., `varying vec2 vTextureCoord;`), that's not worth the effort. If your goal is to compose fragments, doing a simple JS string replace with a token, will do the same thing without a lot of custom build operations or plugins.

I agree with you that **glslify** or **babel-plugin-static-fs** are not great solutions for PixiJS. But Rollup allows us to easily import non-JS as strings and has lots of benefits over Browserify in general.

**Comment by finscn** [comment]
I don't want to solve any problem. 
I just love standard  ES script.  
So I don't like that there are some non-ES-feature in pixi's JS file.

When will you use Rollup  for pixi.js ? Is there a roadmap or plan ?

**Comment by bigtimebuddy** [comment]
As soon as @GoodBoyDigital finishes merging **dev** into **next** then I'm going to start implementing Rollup and Lerna for v5. I'm hoping sometime in the next few weeks.

**Comment by finscn** [comment]
Waiting  that pixi.js use Rollup and Lerna.
