### ISSUE TITLE
[REQUEST]Let Blur support `Working in lower resolution`

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-filters#70]
I read a article :  https://software.intel.com/en-us/blogs/2014/07/15/an-investigation-of-fast-real-time-gpu-based-image-blur-algorithms

there is a tip for optimizing Blur Shader:　Let Blur support `Working in lower resolution`
![image](https://user-images.githubusercontent.com/288367/31723065-7302b07c-b3e3-11e7-989c-03023ca054bb.png)

I hope pixi's blur could support this feature.

example: 
```
blurFilter.resolutionScale = 0.5;
```
The the `blurFilter` will be working in 1/2 resolution.

**Comment by ivanpopelyshev** [comment]
Good idea!

**Comment by finscn** [comment]
@ivanpopelyshev , In fact  I'm very weak at pixi's filter (even I've wrote some filters).
I don't understand many properties of filter , e.g filter.filterCamp filter. resolution.
So.... I've no idea about it.

**Comment by ivanpopelyshev** [comment]
for 512x512 filterArea, for filter with resolution=0.5, filterManager will use 256x256 texture.

**Comment by finscn** [comment]
@ivanpopelyshev , I see.  btw , how about `filterCamp` ? I read the wiki , but I don't understand...
Thanks.

**Comment by ivanpopelyshev** [comment]
Container is rendered in temporary renderTexture, that texture is processed by filter shader onto the screen. 

The problem is that renderTexture has size more than container, its pow2, and not cleared - it was made in v4 for performance on mobiles architectures. Natural texture clamping doesn't work, and if displacementFilter takes a sample at the right or bottom of renderTexture, it gets trash. That's why modified textureCoord has to be clamped before it is passed to texture2d.

**Comment by ivanpopelyshev** [comment]
for (0,0,w,h) clamping must be (0.5,0.5,w-0.5, h-0.5) in pixel coord, because texture2d operates with CENTERS of pixels, not their left-top corner.

**Comment by finscn** [comment]
Thank you very much. I will be thinking about it .

**Comment by finscn** [comment]
`filter.resolution` could let filter  `Work in lower resolution`. So close this issue...
